// Code generated by YangPing. DO NOT EDIT.

package base

type User struct {
	Name   string `json:"name" gorm:"column:name"`
	Age    int    `json:"age" gorm:"column:age"`
	Status int    `json:"status" gorm:"column:status"`
}
