server:
  addr: :8080
  readTimeout: 10000
  writeTimeout: 10000

log:
  logFileDir: logs
  appName: genesis-shunt
  errorFileName: err.log
  warnFileName: warn.log
  infoFileName: info.log
  debugFileName: debug.log
  maxSize: 100
  maxBackups: 60
  maxAge: 3
  development: true
  level: debug

redis:
  addr:
    - 139.9.103.21:16379
  password:
  poolSize:

mongo:
  host: 127.0.0.1:27017
  user: yangping
  password: 123456
  poolSize: 4096
  maxConnIdleTime: 6000

mysql:
  dbName: genesis-shunt
  host: 139.9.103.21:13306
  user: root
  password: 123456
  connectInfo: charset=utf8&parseTime=true&loc=Local
  maxOpenConn: 200
  maxIdleConn: 5

jwt:
  secret: 'genesis.com'
  expireTime: 3600
  issuer: 'genesis.com'
  authKey: 'authorization'