// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/google/wire"
	"genesis/pkg/core/shunt/adapter/http/handlers"
	"genesis/pkg/core/shunt/adapter/http/server"
	"genesis/pkg/core/shunt/application/service"
	"genesis/pkg/core/shunt/repository"
)

// Injectors from wire.go:

func NewHandler() *server.Handlers {
	handler := handlers.NewHandler()
	repositoryRepository := repository.NewRepository()
	appSrvManager := service.NewAppSrvManager(repositoryRepository)
	serverHandlers := server.NewHandlers(handler, appSrvManager)
	return serverHandlers
}

// wire.go:

var providerSet = wire.NewSet(repository.NewRepository, service.NewAppSrvManager, handlers.NewHandler, server.NewHandlers)
