// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"genesis/app/shunt/adapter/http/handlers/business"
	"genesis/app/shunt/adapter/http/routers"
	"genesis/app/shunt/repository/mysqlRepo"
	"genesis/app/shunt/service/bus/impl"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewHandler(db *gorm.DB) *routers.Handlers {
	userMysqlRepo := mysqlRepo.NewUserMysqlRepo(db)
	userServiceImpl := impl.NewUserServiceImpl(userMysqlRepo)
	authHandler := business.NewAuthHandler(userServiceImpl)

	handlers := &routers.Handlers{
		AuthHandler: authHandler,
	}
	return handlers
}
